// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrJDKnecUP4prY2b3mUZEc5FqoDD7xNEA',
    appId: '1:562876610771:web:f778a9861266a83deabc26',
    messagingSenderId: '562876610771',
    projectId: 'cloud-tasks-1fcb6',
    authDomain: 'cloud-tasks-1fcb6.firebaseapp.com',
    storageBucket: 'cloud-tasks-1fcb6.firebasestorage.app',
    measurementId: 'G-F92P2CGN8V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVPgIvk3EjRCHu8KE-O93h5llb-HoA9N4',
    appId: '1:562876610771:android:9e3095bc527be85eeabc26',
    messagingSenderId: '562876610771',
    projectId: 'cloud-tasks-1fcb6',
    storageBucket: 'cloud-tasks-1fcb6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOM3bMH3KF9bmbFvPYGy8uY2POeBs_fHs',
    appId: '1:562876610771:ios:c53dab7c7a8db734eabc26',
    messagingSenderId: '562876610771',
    projectId: 'cloud-tasks-1fcb6',
    storageBucket: 'cloud-tasks-1fcb6.firebasestorage.app',
    iosBundleId: 'com.example.cloudTasks',
  );
}
